name: CI
on:
  push:
  pull_request:
jobs:
  smoke:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Import smoke (no network)
        run: |
          python - <<'PY'
          import importlib.util, sys
          spec = importlib.util.spec_from_file_location('m','jpcc_picker.py')
          m = importlib.util.module_from_spec(spec)
          spec.loader.exec_module(m)
          print('import_ok')
          PY
